//! The news-ticker explainers. Each is tagged with the panel it describes;
//! that panel's frame lights up while its explainer passes the ticker label.

use super::Panel::{self, *};

pub const EXPLAINERS: &[(Panel, &str)] = &[
    (General, "0009 is not a recording. It is a program that composes and synthesises the music live, one sample at a time, forever."),
    (Flow, "Press Tab to switch views. The pipeline view shows the sound as particles travelling through each chain; the engine view opens up each part to show how it works."),
    (General, "Every sample is computed from just four seeds and a counter. The same seeds give the exact same music on any computer, now or in 20 years."),
    (Chord, "Seed 1 shapes the frozen chord, seeds 2 and 3 the two glitch layers, seed 4 the bass. Different seeds give alternate renditions of the piece."),
    (Chord, "The chord uses the notes of D lydian (D E F# G# A B C#). The raised fourth, G#, gives it a bright, floating colour that never resolves."),
    (Chord, "Each chord note is a 3-operator FM voice: one sine wave wobbles the phase of another, building rich overtones out of pure sines."),
    (Chord, "FM ratio picks which overtones appear (whole numbers sound harmonic; 4.003 adds a slow shimmer). FM index sets how bright the tone is."),
    (Chord, "Two FM wirings: a stack (3 modulates 2, which modulates 1) or a pair (2 and 3 both modulate 1). Operator 3 also feeds back into itself."),
    (Chord, "The FM chord is rendered only once, for 8 seconds, at start-up. You never hear it directly, only its frozen spectrum."),
    (Spectrum, "Freezing: the 8 s chord is cut into overlapping windows of 32,768 samples. Each is run through an FFT, and the magnitudes are averaged. Timing is thrown away; only how much of each frequency there was remains."),
    (Spectrum, "An FFT (Fast Fourier Transform) turns a slice of sound into its frequencies: here 16,384 bins, each about 1.46 Hz wide."),
    (Spectrum, "The freezing trick: keep every bin's magnitude, but give each bin a brand-new random phase in every frame. The timbre stays; the motion dissolves into an endless, still cloud."),
    (Spectrum, "Left and right get independent random phases, so the drone is wide and can never cancel itself out in stereo."),
    (Spectrum, "Both channels come from one complex inverse FFT: left rides in the real part, right in the imaginary part. Two transforms for the price of one."),
    (Spectrum, "The bright region is the drone's low-pass filter sweeping across the frozen spectrum. Frequencies above the cutoff are dimmed."),
    (Spectrum, "Bins below 110 Hz are emptied from the frozen spectrum, leaving that range to the bass."),
    (Ola, "Overlap-add: each new frame is shaped by a Hann window (a smooth hump) and overlaps the three before it by 75%."),
    (Ola, "Why 75%? Four squared Hann windows, each a quarter apart, always add up to exactly 1.5, so random-phase frames blend at perfectly steady loudness."),
    (Ola, "A new frame starts every 8,192 samples (171 ms). Each is a different random grain of the same frozen sound."),
    (Ola, "To keep the browser version glitch-free, each frame's work is sliced into 25 small jobs (fill the spectrum, bit-reverse, 15 FFT stages, apply the window), one every 256 samples."),
    (Cycles, "Seven slow LFOs (low-frequency oscillators) shape the form. Their periods are 41, 61, 97, 113, 151, 233 and 307 seconds, all prime numbers."),
    (Cycles, "Because every period is prime, the combined pattern repeats only after their product: 296,097,754,097,441 seconds, about 9.4 million years."),
    (Cycles, "LFO positions are calculated from the sample counter (clock mod period) instead of being added up step by step, so they never drift, however long the piece plays."),
    (Cycles, "The LFOs mix into six controls: drone filter openness and resonance, the density of each glitch layer, bass brightness and bass swell."),
    (Glitch, "Glitch layer 1 loops 7 sixteenth-note steps; layer 2 loops 11 eighth-note steps. 7 and 11 share no factors, so the layers drift in and out of phase."),
    (Glitch, "Cyclic repeats: each layer plays its pattern 3 to 9 times, then mutates one step by replacing it, clearing it, re-pitching it, or rotating the whole loop."),
    (Glitch, "Every step has a threshold. It sounds only while the layer's density (set by the slow LFOs) is above it, so patterns thin out and fill back in over minutes."),
    (Glitch, "Ratchets: some steps fire 2 to 4 times within their slot for a stuttering roll."),
    (Glitch, "B: Blip. An FM tone crushed to a few levels and sample-held: deliberately aliased digital grit."),
    (Glitch, "S: Stutter. A tiny grain copied from the last 1.4 s of the drone and looped, sometimes backwards: the drone chopped into rhythm."),
    (Glitch, "P: Ping. Two sines at a 1 : 2.756 ratio (the inharmonic partials of a small bell) with a long exponential decay."),
    (Glitch, "T: Tick. White noise, differentiated (each sample minus the one before) so only its crackly top end remains."),
    (Glitch, "C: Click. A few milliseconds of square-wave buzz, the sound of a digital dropout."),
    (Glitch, "X: Crush. Noise held for several samples and quantised to three levels: a burst of broken data."),
    (Glitch, "All glitch pitches come from the same D lydian scale as the chord, so even the noise belongs to the harmony."),
    (Echo, "The echo is a ping-pong delay. Sound enters on the left, then bounces right, left, right every 3/16 of a bar (535 ms)."),
    (Echo, "Each bounce passes through a low-pass filter, so repeats grow darker as they fade, like tape or air."),
    (Reverb, "The reverb is a feedback delay network: 8 delay lines of 63 to 169 ms, mixed by an 8x8 Hadamard matrix and fed back into themselves."),
    (Reverb, "A Hadamard matrix holds only +1s and -1s. It mixes every line into every other without adding or losing energy, so the tail grows dense and smooth."),
    (Reverb, "Each line's feedback gain makes the tail fall 60 dB in 18 seconds. A low-pass in every loop makes the highs die sooner, like a real room."),
    (Reverb, "Before the reverb, four all-pass diffusers per side smear sharp transients, so glitches bloom instead of fluttering."),
    (Reverb, "The reverb input is high-passed at 180 Hz, so 18 seconds of tail never build up into low-end mud."),
    (Bass, "The bass is a 2-operator FM tone on D2 (73.4 Hz) plus a pure sine an octave below, on D1 (36.7 Hz)."),
    (Bass, "The FM bass is detuned from the sub by up to 1.5 cents, so the two beat slowly against each other."),
    (Bass, "When the bass-brightness LFO rises, it raises the FM index and opens the low-pass (140 to 500 Hz) together."),
    (Output, "Master: a DC blocker removes any offset, then a tanh soft clipper rounds peaks off smoothly instead of clipping them."),
    (Output, "The piece fades in over its first 10 seconds. Rendered files fade out over their last 40 seconds; live playback never ends."),
    (Output, "What you see is in sync with what you hear. The engine runs about 85 ms ahead, and each snapshot waits until its samples reach the sound card."),
    (General, "The engine has zero dependencies. It has its own sine, exponential, tanh, random numbers and FFT, built only from + - x / and square roots."),
    (General, "Why not use the system's sin()? Maths libraries round differently between operating systems and versions, enough to make two renders of the same track differ."),
    (General, "The browser version is this same Rust code compiled to WebAssembly. A test hashes 30 s of output from both builds, and the hashes match bit for bit."),
    (General, "Output is block-size independent: whether the sound card asks for 128 samples or 65,536 at a time, every sample comes out identical."),
    (General, "Everything runs at a fixed 48,000 samples per second, in 64-bit floating point, from a single integer sample clock."),
    (General, "These visuals only read from the engine and never touch it. The golden-hash test proves the sound is identical with or without them."),
    (General, "Random numbers come from SplitMix64, a tiny integer-only generator whose output is fully defined by its arithmetic, on every machine."),
];
